### ISSUE TITLE
Use project-related Cmake variables to simplify CMakeLists.txt in the applications

### ISSUE THREAD

**Issue by giorgiobornia** [FeMTTU/femus#12]
See how the variables PROJECT_SOURCE_DIR and PROJECT_BINARY_DIR behave.

**Comment by sbna** [comment]
We have only one project so:
 PROJECT_SOURCE_DIR is the folder where you clone the code
  PROJECT_BINARY_DIR is the folder where you put the binaries

**Comment by giorgiobornia** [comment]
We also have all the Projects in the applications, so I believe we can use those two variables to simplify all of them, and avoid to explicitly write down the name of the folder in the application CMakeLists.txt.

**Comment by giorgiobornia** [comment]
Simplified all application Cmakelists.txt, and made a unique macro for applications and tests instead of two.
