### ISSUE TITLE
Topology print in XDMFWriter in parallel

### ISSUE THREAD

**Issue by giorgiobornia** [FeMTTU/femus#25]
It is correct in serial, but not in parallel.

**Comment by eaulisa** [comment]
Yes, confirmed. It works in serial
Before I made a push (for the DZ check) in the moving mesh solution

**Comment by giorgiobornia** [comment]
By the way, I still don't understand why there are float arrays. I will convert them to double very soon...

**Comment by eaulisa** [comment]
I think what is missing is some localize_to_one for mysol. I am also not sure how it is running right now in parallel since we are asking to get part of mysol that do not belong to iproc

**Comment by giorgiobornia** [comment]
I am looking at the HDF5 file and the coordinates have many zeros which is not realistic.

**Comment by eaulisa** [comment]
yes becuase there is no localize to one and you are picking values starighforward on parts of the parallelel vector that don not belong to iproc 1

**Comment by giorgiobornia** [comment]
I believe that the print should be serial here, I don't know how it is for the other formats.

**Comment by giorgiobornia** [comment]
I fixed it. I will merge it soon.
