### ISSUE TITLE
SetBoundaryCondition is very poor as a function pointer, I cannot access anything. I propose to add MultiLevelProblem as argument

### ISSUE THREAD

**Issue by giorgiobornia** [FeMTTU/femus#33]
In this way can access mesh information, parameters, nondimensional values... Do you guys agree? Please...

**Comment by giorgiobornia** [comment]
There is one thing to pay attention to though. MLProblem is instantiated AFTER calling GenerateBdc, so we should move that call (of course, MLProblem has to be passed as a const pointer or reference)

**Comment by eaulisa** [comment]
Okay, I think is a good idea that all user defined functions should have a ml_problem as an argument.
However set bound is called by ml_solution, which can be defined even if ml_problem has not been defined, so some precaution should be used.

**Comment by giorgiobornia** [comment]
Ok, I am thinking of a good old pointer which can be null...

**Comment by giorgiobornia** [comment]
Another option would be to associate the boundary condition flags to the Systems, rather than to the Solutions. One can think that the boundary conditions are related to the particular operators of the equation at hand, so associate them to each system (something like system.SetBoundaryConditionFunction() ). At that point, the MLProblem is already accessible.

**Comment by giorgiobornia** [comment]
For the time being, to avoid changing the interface in every application, I will create a duplicate function GenerateBdc_MLProb that receives a pointer to the MLProb as an additional argument.
I will also need a duplicate function pointer with that argument. 
If we agree that the new version is better (which I support), we can replace the interface in all applications. Clearly, this will imply that the call to GenerateBdc will happen AFTER the instantiation of the MLProblem.

**Comment by giorgiobornia** [comment]
And there is another change that I propose for the SetBoundaryCondition function, which is to have a vector argument xyz instead of three separate arguments x,y,z. This works flexibly for any dimension, without putting any zeros (and it also compactifies the notation).

**Comment by eaulisa** [comment]
On this I think we all agree

**Comment by giorgiobornia** [comment]
Similar considerations hold for the function pointer for Initialize in MLSol.
